In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np
from scipy.stats import linregress


# Study data files
rest = "NYC_Restaurant_Inspection_Results_Clean2020.csv"

# Read the mouse data and the study results
Rest = pd.read_csv(rest)

# Display the data table for preview
Rest.head()

,CAMIS,DBA,BORO,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,...,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,INSPECTION TYPE,INSPECTION TYPE GENERAL,Latitude,Longitude,YEAR,ADDRESS
0,50090691,SALIM KENNEDY FRIED CHICKEN,Queens,HILLSIDE AVE,11432.0,7183744616,Bangladeshi,2/20/2020,Violations were cited in the following area(s).,08A,...,N,20,NaN,NaN,Cycle Inspection / Initial Inspection,Initial Inspection,40.709572,-73.796195,2020,"16614,HILLSIDE AVE,11432"
1,50095392,HOPE TO SEE YOU,Queens,39 AVENUE,11354.0,7188881669,Chinese,1/2/2020,Violations were cited in the following area(s).,10F,...,N,13,A,1/2/2020,Pre-permit (Operational) / Initial Inspection,Initial Inspection,40.759099,-73.834139,2020,"133-42,39 AVENUE,11354"
2,50033575,JACQUES TORRES ICE CREAM,Manhattan,EAST 42 STREET,10017.0,2129837353,"Ice Cream, Gelato, Yogurt, Ices",3/9/2020,Violations were cited in the following area(s).,08A,...,N,40,NaN,NaN,Cycle Inspection / Initial Inspection,Initial Inspection,40.752094,-73.977604,2020,"89,EAST 42 STREET,10017"
3,50089342,REGAL CINEMAS ESSEX CROSSING,Manhattan,DELANCEY STREET,10002.0,2124755768,American,3/13/2020,Violations were cited in the following area(s).,10F,...,N,2,A,3/13/2020,Pre-permit (Operational) / Initial Inspection,Initial Inspection,40.718327,-73.987518,2020,"129,DELANCEY STREET,10002"
4,50033875,ARIANA'S,Staten Island,SOUTH BRIDGE STREET,10309.0,7189678500,Italian,1/23/2020,Violations were cited in the following area(s).,02H,...,Y,9,A,1/23/2020,Cycle Inspection / Initial Inspection,Initial Inspection,40.525075,-74.236617,2020,"60,SOUTH BRIDGE STREET,10309"

In [4]:
Rest.nunique()

CAMIS                      8738
DBA                        7712
BORO                          6
STREET                     1436
ZIPCODE                     200
PHONE                      8573
CUISINE DESCRIPTION          82
INSPECTION DATE              70
ACTION                        5
VIOLATION CODE               59
VIOLATION DESCRIPTION        59
CRITICAL FLAG                 2
SCORE                       100
GRADE                         6
GRADE DATE                   65
INSPECTION TYPE              14
INSPECTION TYPE GENERAL       5
Latitude                   8037
Longitude                  8048
YEAR                          1
ADDRESS                    8242
dtype: int64

In [8]:
Rest["DBA"].unique()

array(['SALIM KENNEDY FRIED CHICKEN', 'HOPE TO SEE YOU',
       'JACQUES TORRES ICE CREAM', ..., 'KING WOK', 'LOT 45', 'PYRAMID'],
      dtype=object)